<div class="row">

    <div class="col-md-12">
        <form name="upload-form" id="upload-form" method="post" enctype="multipart/form-data">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Upload de Certificados</h3>
                </div>
                <div class="panel-body">

                    <div class="form-group">
                        <label class="control-label col-sm-2" for="nome">Nome do Certificado:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="nome" placeholder="Informe um nome para este cerfificado">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="certificado">Certificado (PEM):</label>
                        <div class="col-sm-10">
                            <input type="file" name="certificado">
                        </div>
                    </div>

                </div>
                <div class="panel-footer">
                    <input type="submit" class="btn btn-primary btn-xs" value="Enviar">
                    <a class="btn btn-default btn-xs" role="button" href="<?php echo $this->url('certificate'); ?>">Voltar</a>
                </div>
            </div>
        </form>
    </div>

</div>
