<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Excluir Certificado</h3>
                </div>
                <div class="panel-body">
                    <p>Tem certeza que deseja excluir o certificado?</p>
                    <p><b>Nome:</b> <?php echo $this->nome; ?></p>
                    <input type="hidden" name="id" value="<?php echo $this->id; ?>">
                </div>
                <div class="panel-footer">
                    <input type="submit" class="btn btn-primary btn-xs" value="Confirmar">
                    <a class="btn btn-default btn-xs" role="button" href="<?php echo $this->url('certificate'); ?>">Voltar</a>
                </div>
            </div>
        </form>
    </div>
</div>
